"""add geo_mode column to nodes

Revision ID: 09adb90e970f
Revises: 6b82cec33861
Create Date: 2025-10-23 19:29:15.693989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09adb90e970f'
down_revision = '6b82cec33861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('geo_mode', sa.Enum('default', 'custom', name='geomode'), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'geo_mode')
    # ### end Alembic commands ###
