"""add data_limit and users_limit to admins

Revision ID: a9584d547b24
Revises: 09adb90e970f
Create Date: 2025-10-25 14:30:33.280965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'a9584d547b24'
down_revision = '09adb90e970f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {
        column["name"] for column in inspector.get_columns("admins")
    }

    data_limit_values = {}
    users_limit_values = {}

    if "data_limit" in existing_columns:
        rows = bind.execute(
            sa.text("SELECT id, data_limit FROM admins")
        ).fetchall()
        data_limit_values = {row.id: row.data_limit for row in rows}

    if "users_limit" in existing_columns:
        rows = bind.execute(
            sa.text("SELECT id, users_limit FROM admins")
        ).fetchall()
        users_limit_values = {row.id: row.users_limit for row in rows}

    if "data_limit" in existing_columns or "users_limit" in existing_columns:
        with op.batch_alter_table("admins") as batch_op:
            if "data_limit" in existing_columns:
                batch_op.drop_column("data_limit")
            if "users_limit" in existing_columns:
                batch_op.drop_column("users_limit")

    with op.batch_alter_table("admins") as batch_op:
        batch_op.add_column(sa.Column("data_limit", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("users_limit", sa.Integer(), nullable=True))

    if data_limit_values:
        update_stmt = sa.text(
            "UPDATE admins SET data_limit = :data_limit WHERE id = :id"
        )
        for admin_id, data_limit in data_limit_values.items():
            bind.execute(
                update_stmt, {"data_limit": data_limit, "id": admin_id}
            )

    if users_limit_values:
        update_stmt = sa.text(
            "UPDATE admins SET users_limit = :users_limit WHERE id = :id"
        )
        for admin_id, users_limit in users_limit_values.items():
            bind.execute(
                update_stmt, {"users_limit": users_limit, "id": admin_id}
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'data_limit')
    op.drop_column('admins', 'users_limit')
    # ### end Alembic commands ###
