"""add data_limit and users_limit to admins

Revision ID: a9584d547b24
Revises: 09adb90e970f
Create Date: 2025-10-25 14:30:33.280965

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a9584d547b24'
down_revision = '09adb90e970f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('data_limit', sa.BigInteger(), nullable=True))
    op.add_column('admins', sa.Column('users_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'data_limit')
    op.drop_column('admins', 'users_limit')
    # ### end Alembic commands ###