"""Add data_limit and users_limit to admins

Revision ID: f1a2b3c4d5e6
Revises: cbc81a0e2298
Create Date: 2025-10-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'cbc81a0e2298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('data_limit', sa.BigInteger(), nullable=True))
    op.add_column('admins', sa.Column('users_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'users_limit')
    op.drop_column('admins', 'data_limit')
    # ### end Alembic commands ###
